# This is the Netlify configuration file.

[functions]
  # This tells Netlify to include your data file in the function's deployment package.
  # The path is relative to the root of your project.
  included_files = ["achievement-dashboard/data/achievements.json"]